import { FC, useMemo } from "react";

interface Props {
  initialAmount?: number; // available stock
  amount: number; // current selected qty
  setAmount: (amount: number) => void;
  step?: number; // default 1
  cap?: number; // optional cap for very large stock (e.g., 20/50)
}

/**
 * Quantity switcher as a minimal dropdown (Zara/Apple vibe)
 * - Underline-only <select>, compact typography
 * - Options generated by stock, step, and optional cap
 * - Keyboard & native mobile picker friendly
 */
const QuantitySwitcherDropdown: FC<Props> = ({
  initialAmount,
  amount,
  setAmount,
  step = 1,
  cap,
}) => {
  const max = useMemo(() => Math.max(initialAmount ?? 0, 0), [initialAmount]);
  const effectiveMax = useMemo(() => {
    if (!max) return 0;
    const capped =
      typeof cap === "number" && cap > 0 ? Math.min(max, cap) : max;
    // ensure step alignment
    return Math.max(step, capped - ((capped - 1) % step));
  }, [max, cap, step]);

  if (!initialAmount || initialAmount <= 0) {
    return (
      <div className="rounded-md text-[13px] bg-neutral-100 text-neutral-600 dark:bg-neutral-800 dark:text-neutral-300 p-3">
        Үлдэгдэл дууссан байна. Дэлгүүрийн ажилтантай <b>7777‑7777</b> утсаар
        холбогдоно уу.
      </div>
    );
  }

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const v = parseInt(e.target.value, 10);
    if (!Number.isNaN(v)) setAmount(v);
  };

  return (
    <section
      className="inline-flex flex-col gap-1"
      aria-label="Тоо ширхэг сонгох"
    >
      <label
        htmlFor="qty-select"
        className="text-[12px] uppercase tracking-wide text-neutral-500 dark:text-neutral-400"
      >
        Тоо ширхэг
      </label>

      <div className="relative w-28">
        {/* Native select, underline style */}
        <select
          id="qty-select"
          value={amount}
          onChange={handleChange}
          className="appearance-none w-full bg-transparent text-[15px] md:text-[16px]
                     text-neutral-900 dark:text-neutral-100
                     border-0 border-b border-neutral-300 dark:border-neutral-700
                     focus:border-b-2 focus:border-neutral-900 dark:focus:border-white
                     outline-none py-1.5 pr-6 transition-[border] duration-150"
          aria-describedby="qty-help"
        >
          {Array.from(
            { length: Math.floor(effectiveMax / step) },
            (_, i) => (i + 1) * step
          ).map((n) => (
            <option key={n} value={n} className="bg-white dark:bg-neutral-900">
              {n}
            </option>
          ))}
        </select>
      </div>

      <p
        id="qty-help"
        className="m-0 text-[12px] text-neutral-500 dark:text-neutral-400"
      >
        Нийт үлдэгдэл: {max} {max === 1 ? "ширхэг" : "ширхэг"}
      </p>
    </section>
  );
};

export default QuantitySwitcherDropdown;
